apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: bitnami
  namespace: keycloak
spec:
  interval: 15m
  url: oci://registry-1.docker.io/bitnamicharts/keycloak
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  chart:
    spec:
      chart: keycloak
      version: 26.3.3
      sourceRef:
        kind: OCIRepository
        name: bitnami
  interval: 15m
  timeout: 5m
  releaseName: keycloak
  values:
