apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: keycloak-repo
  namespace: keycloak
spec:
  interval: 5m 
  url: oci://registry-1.docker.io/bitnamicharts
  type: oci

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  chart:
    spec:
      chart: keycloak
      version: 26.3.3
      sourceRef:
        kind: HelmRepository
        name: keycloak-repo
  interval: 15m
  timeout: 5m
  releaseName: keycloak
  values:
