apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami-repo
  namespace: keycloak
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 15m
  timeout: 5m
  releaseName: keycloak
  chart:
    spec:
      chart: keycloak
      version: "26.3.3" 
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
  values: {}

