apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: keycloak-repo
  namespace: keycloak
spec:
  interval: 5m
  url: oci://registry-1.docker.io/bitnamicharts/keycloak
  ref:
    tag: 26.3.3  # Specify the version you want
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 15m
  timeout: 5m
  releaseName: keycloak
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: OCIRepository
        name: keycloak-repo
  values: {}

