apiVersion: v1
kind: Secret
metadata:
    name: ozoo-app-secrets
type: Opaque
stringData:
    DATABASE_URI: ENC[AES256_GCM,data:NTvjLAHlQgBhh2cfSt8ITyE3CgjAzmyxj63jWAnb0DlX8onEMeXEv9DxNjRbBsJNDPUlnfYphjU=,iv:LXdVCEAlwVTGwk82R+r3MqVipJRQzDhWsLTe7gObhbs=,tag:oNwyadcELRnWxxgpDfEaCA==,type:str]
    MONGO_INITDB_DATABASE: ENC[AES256_GCM,data:8xKrxg==,iv:VpGe3vXizF7so+5pxTrrl7YYzoByAIeFeIpcRrjfDGc=,tag:U4y+Z29V6nTN88lEBnlkVQ==,type:str]
    MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:60kN3wMwnXnW3hCvAxQQXFS/lbRR2VszmzZzpZIVni4=,iv:D4vOb/pWcFksNPTZqRBsSQVkbC5TNZXBJs+io0jPJLo=,tag:GUP/KvN4cuGa1lU7jN1Zlg==,type:str]
    MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:HCpCJg==,iv:mNdISeRYb7HETJke3i3LzFrbShVfS1M9zQgbmPAZr5c=,tag:hUao7Of3VyWTVAEYJKwvjw==,type:str]
    PAYLOAD_SECRET: ENC[AES256_GCM,data:unkgqZ0VC9gxE06oxO/Z5u9lzL2pIQjBBI4K5oKHRag=,iv:tO2p0oyyp2kW9+m3alVMeav4NJNgh8Ls9R32VW4vm/8=,tag:BA5HwWRI3MrAKDYb/KTu2A==,type:str]
    PREVIEW_SECRET: ENC[AES256_GCM,data:g85e+lulRLpQhuxPrrlxMaDj6N24f06VrcwMcg38G18=,iv:7hu4BbAoMxZA4G3p4f5dr2H8s64W8yHcSru3Arv/mjA=,tag:yKecsRnNKAcsZPDXB9xChQ==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:Bv6QVaqnuXV4ssASaBq8QejbXg==,iv:gk+2NmU+q9cq0Nsj725W6x5ZTDQgyLpciWY2R3bBTpI=,tag:08R4/V/lG0bmXy/xTZvQQg==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:Nf5/,iv:+6auSZ/XvPZTBRxF+Nz8nHrKRZ4K6rqP1xgRfYAvge4=,tag:mkizece5Tbr7VOvLpDq0FA==,type:int]
    SMTP_USER: ENC[AES256_GCM,data:uTilKPFVMwwkwO5z+zLcqG94ItrekJmL4YRZ/Sg=,iv:ELnds5fPAcqKYTgtJL6lBZPVXXX4uLSn88qepgY6lJQ=,tag:pH2/NBg9yW5odscZVj9c5Q==,type:str]
    SMTP_PASS: ENC[AES256_GCM,data:EuLUOCmoW1c5sAOvxF3JHw==,iv:2vEEuyIEI4i9DGhVERh87aQQMr2k+CWVEgRazBYIHvA=,tag:lbnjGr8hhDtTq+AM3U7n+Q==,type:str]
    FROM_EMAIL: ENC[AES256_GCM,data:SCikt6RiXsuCsmnAQuH8OxjPNhwn15mU43gbZQw=,iv:Vt2UO1fmBYtXHXOkkpslWE3+2o1aAsFlKwVFvDlEhgA=,tag:4qMSlJpHPcE8rnAa9RzZTg==,type:str]
    FROM_NAME: ENC[AES256_GCM,data:COXvksgynCDekA==,iv:5FJr9dgjWl8X1cGw9dRpWPeTf00rUxrsiEzkleg1qcQ=,tag:QGEhDOiaNgFe9xUvgdr9Bw==,type:str]
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:RR3em/eESQYPCMYDWIVI8Mjgyckg7/fVlxeYwH3lAeVQ+9ROjqoUlt8IjwqDp2fgUQXThfMdgt2Xsrc1LGdqaqzIXyik5JrU7dCclRDHTf3HoSOuLCgpsprdIYUzpg0ceGxKDGyhSpe38b4=,iv:I3beOG6Ebonkq098U4SQbHMGBvtGezzMdzVu1oiKAV0=,tag:5IQ0zpTRLfKjGD3dGC39gA==,type:str]
    STRIPE_WEBHOOKS_SIGNING_SECRET: ""
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ENC[AES256_GCM,data:6vzzSp2L9bk2PDnD2sHL8SQwB28aKmwer6AHNdOgM3TcXv4dH8CIPcp36SREnCfyFrfwAtycegr9Rh8eiCR3MydFWrU/Z1SC9PQ67KzsQtgIcTthAEMKj1/SYxOn6AP3noj9A60xVP7rqBI=,iv:zpslyrJ8BzzFMNKxoCRl/7TvFWw1wq8fnYSK52rTWKk=,tag:N/iOLagqVFZWJfgaTGL0sA==,type:str]
    NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: ENC[AES256_GCM,data:pmJhGfFaXATpGzUe2bKdTzqGebssXwf/zKchh2dlUZc=,iv:zfEDVNjgOsonuLu8c68JWAWR13UFel+HFUHS+6mhVQc=,tag:BiDhHi4Ha/y6h86CvYBUhg==,type:str]
sops:
    lastmodified: "2026-03-15T10:31:48Z"
    mac: ENC[AES256_GCM,data:GRVVZNnFNydAT0+6abG1V2ilFuPOyLyUYE12qolIJUtybbpFfBxLYOX1qstVhG/5foe7WHTZZa3CJCJ3u+fF8a45XA40xBhHkBTazgAPD5jWu+u4oHJfjNWjrRwi+QglvXAIbpxTuBV3bNQ8wEawk+e/c4xsQXdGwnwbuaqh2Y4=,iv:RWne868Vws4iJWO1liMcd4YSZEp4PvQVldu6Cb3gN4c=,tag:oKgX9hvSu3DUIfkZrSqkHQ==,type:str]
    pgp:
        - created_at: "2026-03-15T10:31:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DVb+0b1rhfkgSAQdAw8fL6FII4Zi62l96ZMQjEPlYeybIX5oLRc6prci88Csw
            kz3rfPZJrIx8bmuX8FgTFUITtT5fB9QKkQZYICP/ufcc7CQLxcwxFcfI3xIcY7nA
            0l4B1L9nIM/y67XPesB08NnN/GhK7RP7AsXdkml6iWEmtSA2ZGGv6WbMMahD45bZ
            MhQSGPdMNAQ0WGs29RTep4lQWMYpXb66t5AOkG0VTdEC6Oq3pnZ7dFCvN2aW89Ss
            =OjOL
            -----END PGP MESSAGE-----
          fp: 1943731352CACC3B2164E3EED2473B882A11DCBA
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
