apiVersion: v1
kind: Secret
metadata:
    name: ozoo-app-secrets
type: Opaque
spec:
    stringData:
        DATABASE_URI: ENC[AES256_GCM,data:0aak2yADGAtOWPkFYOwE6JqG1hwjSuPz3IF7QwNyCSTgwhafaKwHteYK6EZY4G5Hp8VclwCtFo0=,iv:OAWPDbtvAH4QWe8J7bFy/QnFRDDQfRxXV/A7hz1TyYs=,tag:P0f8SdBlzrON3v6zZwVFTg==,type:str]
        MONGO_INITDB_DATABASE: ENC[AES256_GCM,data:8Istfg==,iv:YP4/fU7cM9lY6RNNH21wnFE1eTPM5jORcXAXA1cNkCU=,tag:sKSRQdREtX1+thkrZDloBg==,type:str]
        MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:jYgdX1nUxUZk8HPYFCN+Pz2zb+BozrT6qV840kEgaik=,iv:uD2OULsb4SXV7NYXvB839o4YQXtzF7OZd28sv8V9m7o=,tag:kTfYFwlZ66dqOwrHw6ndLQ==,type:str]
        MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:ERozlA==,iv:lTeJrRJHQmt68A3CMRc/b00Bsq/+73Y++OvHM3bmbfs=,tag:9WuC2eYYKjUYlPygAKhXtA==,type:str]
        PAYLOAD_SECRET: ENC[AES256_GCM,data:HXNIEhNi9oLprABIbExx+pA9GKXC2fO0IWpZ/1rurhE=,iv:/JB6fY2HhR8OZpVMmKA7Hv3eW/w22VTIKreh411cRMk=,tag:8nVJhATeLRXgbznAOtIR5Q==,type:str]
        PREVIEW_SECRET: ENC[AES256_GCM,data:k3iuaOkQ4EmUeKTmTg/Ice9iQduwRiK3sViliaNL3LU=,iv:HYgrd9kPZSKkM7Inj7Na+PYk1OMGzzEMLadJFexlWjI=,tag:4F60ZWDONSJQDD6BYMjebA==,type:str]
        SMTP_HOST: ENC[AES256_GCM,data:PSO10eqwQJZlf9TbM/1rFwgbVg==,iv:mdwQpk3G7IQx7WQ/qYf27ZjXFK7JaQHsP6xtd00zsBw=,tag:SLfAacSQcfeZUn73scXEOQ==,type:str]
        SMTP_PORT: ENC[AES256_GCM,data:1/hC,iv:ibwDh2zLb8IvoMTpTkCZOtP2/esWgUz2ruLW+usvtuw=,tag:pcO+IDJkp/7vWlELVlpuDA==,type:int]
        SMTP_USER: ENC[AES256_GCM,data:slZocgBIwWzDucQTJc3gZFKmH7DqkSyuilj7Kmg=,iv:mnvVCFvHqu/kTWd2dJOGAprXCxsid+ZPmTVFo1gImCE=,tag:WbWLCU+8L3OFGpSa+GutvA==,type:str]
        SMTP_PASS: ENC[AES256_GCM,data:3BLBxoOgPAIe8gwbR/YtEw==,iv:Ul4y2KilsxI0/ZBquVW0xHGccCbAf4rpPrQPP8WJ59Y=,tag:IJ8kEJ8FY9jQubSFlb52Tg==,type:str]
        FROM_EMAIL: ENC[AES256_GCM,data:PuORBEqTZMwpHEpWi53LhpgqOS22RgYQfkGlE2A=,iv:VL6jysuoLy14a3zOxK3BfulkmYDpB+9RuIrHEJNyASY=,tag:qAENqLVXeaaPR2So8bO6Pw==,type:str]
        FROM_NAME: ENC[AES256_GCM,data:4dlVWotJgvpbng==,iv:wFKIpeeWI3tviONituhErIeOsJl/W3djuRKjsnerzaM=,tag:5rA4gEd1UZ60lHx8LN51Ow==,type:str]
        STRIPE_SECRET_KEY: ENC[AES256_GCM,data:8C8z1y4Q2QWVFmd8L5qpy4G5f88a6+cPomk9TFkKCG1Byesfm4Ko/MkHmUHHMVyzbOYt0iC/JGBhunP2zJUa86jKZCUV26xOHgqTgxvOTvmDaz2Hjq7zJXo+/0r5zhzAcwypX9nfKyBzACE=,iv:Sq4JQM6C/J/0e96r8WX5AaWUw1Z/m6KgPjpQ5sAh/FA=,tag:Tft/5Tw70/8Tc6s6JFGMUg==,type:str]
        STRIPE_WEBHOOKS_SIGNING_SECRET: ""
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ENC[AES256_GCM,data:Sn+I+c2yqRvwMV1GvUwI/2SLwbw90WvLvBAD66XhLkKgpeqEfuumqugsNmCLha3KAPoDD/kdHiTROoYrolGxk4PmhiW7LeCh5ryOlFQLxfi3ROpcJ7WyFMRyCbyzj64bJjpElwA8VBa/spE=,iv:tt7Atba4TCVytRDe5pxEQSebozd0n/RK5riHKzrlako=,tag:Q0yS2JeYsz6tFlNgJTx9aw==,type:str]
        NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: ENC[AES256_GCM,data:41E7448UBThOHc2NcNhXjiVs5mQqpu3Iobcpx9F/Kcg=,iv:eOLLDUzIcQEy8LnArKT2+eg0TKf3pIXZ2u5wbgYas6o=,tag:i78Tcgvgl2XLd+Aco2kIfw==,type:str]
sops:
    lastmodified: "2026-03-09T09:05:49Z"
    mac: ENC[AES256_GCM,data:tdyq38L7u4Hvmqzp/hsYRSC9LEMdahpKPU5HMybcUmwiD10GUdKps60jYBxAXRhoN5/paro072zqiqEXVCZcOpi7n37PnEfmJgO4pAZASf7S5LPo0z82L7JGi0Rk8JTCyIA/cnTt/JBaR+Bkc24roJtE9o+bWewRdWa5pCce3mM=,iv:pjXNw3N1msxmUuM248UaOPUtmLZZJBI1m4My6bmSwxs=,tag:eWgjiHKGgAZh3R5aG4Q1eA==,type:str]
    pgp:
        - created_at: "2026-03-09T09:05:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D5oAJD2lfBHYSAQdAw6KSnF5umKiMhcazqTCSHQyLGXKQfFbOVlVij7g53DIw
            3ahwWrCDl4FsL7Gazru1IaxsoWrMHbQM7GfiWpo80LHTtY8HOJ1Ro6ZqdQkvp8t+
            0l4BrXGwBZnLDKB+aDk30pd84pmbpstHlAs7FOBxEiX/IT/h0P61h/Bn+LiMcBme
            2WfXaRLqWNQ2L8LrI/DbUntK4w4/n0WQAShK7J1poqt+ZdM66WdSuEZi1svbQwiV
            =EmO6
            -----END PGP MESSAGE-----
          fp: BF57BF7A6DBE01B12D4D56ACA7A4F911668ACE71
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
