apiVersion: v1
kind: Secret
metadata:
    name: ozoo-app-secrets
type: Opaque
stringData:
    DATABASE_URI: ENC[AES256_GCM,data:dDNPh4QvsspgB1ma/mmrsidn75OjaJQHm8BG89PX1KKwDsWNIdPfakzv+2NbE9CjOcF6jBPz1qEYiQ==,iv:wnYeC19/6NN5KZ42PsQ4Ycs+KlF0t+J3EN1+xbZsaMc=,tag:k1alVh46St9pgBqSR7QmLg==,type:str]
    MONGO_INITDB_DATABASE: ENC[AES256_GCM,data:KHSEFw==,iv:R88n56I+u0Wvyo6ywzqys2dHM+6vtyBvMIgX89yOjDU=,tag:hI5uTissFnRHuwvXnu5LTw==,type:str]
    MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:OWjdBXtMpOVFkmnxmPTqfiXcVzFyH8SsoHRkQ+AFVV0=,iv:FVtxiHLA4wBaHWSNaYaIkB/lSFX0spo+1PinEwXd45w=,tag:ewcgzgC142nYacEsjDLTdQ==,type:str]
    MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:JC+21Q==,iv:kMhxk7xeYrQ8KBQSxfc7pxUIE98AAGqXrO6RrECnrUo=,tag:5WAIGSrwRZM0j7dTCRTqog==,type:str]
    PAYLOAD_SECRET: ENC[AES256_GCM,data:gx/caMdTpBDQEGq6iffkdgSc9u+mMYVLvHrd5oF0GEY=,iv:IssgMn89Yg6oR0Y6jDhB/kkTLRclAWWDp7TRyHM/MIM=,tag:W9HO6ue17aGX0ZwOb0OgBQ==,type:str]
    PREVIEW_SECRET: ENC[AES256_GCM,data:VFwbHF/BP+CTLVWEC9KXP1fREWKDdotayasD/JhMcl8=,iv:+uShrr0l8NM2IuzN5sP8L9le/KN0f/s2hKDcZPt4ypY=,tag:UsZsgP2cw5ETpyQHsy40SA==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:yde679KZqwIVTRjyl4atqSL7og==,iv:93Colk1Mu7slQcgblU0R5JMMle/tFy5dj6EBCjYDzZ0=,tag:LBF+cnj5cuZ0ZTZ6PwVBrA==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:Dop9,iv:YMlF9d4Ue77GiWNO0MWzSO9697iqH5kiQC+JOFVM49Q=,tag:QNcfWJuWWfltaN7kyGMSRQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:d6ojTx7PQoHEwmOQcwRXJpgCZzKA4zbnixfl+gc=,iv:+jF+utsOlj8hoo6vhXDfeXU0fbN24JIC+zGaq8teNgc=,tag:kz+VJmX30p+rGHmrcDZlgA==,type:str]
    SMTP_PASS: ENC[AES256_GCM,data:+M6IbgxWcMs4xFI1QpslTw==,iv:auc3QiGUgxxgci5dL47/ETqMGWW4OqZZFoXFUikSFa8=,tag:tbxAf2jNPFAVZXTNeIqwxA==,type:str]
    FROM_EMAIL: ENC[AES256_GCM,data:WsprT2DHaFvB62ePII4Pi2LlHhJv2NVs00IP/tI=,iv:ZSUiWMzwWYQQ0XJVV6EcuCC25d2d9jtnsnfPu3jT92Q=,tag:pMQj991UeAEzkkS9XtopEA==,type:str]
    FROM_NAME: ENC[AES256_GCM,data:RD1emdMPvGY4sQ==,iv:bXvtw7ovWftT5RTY0MGdujoV0KJed9CKr6h/saMmYLA=,tag:lEse11RA1p3IDMKgjiqa9w==,type:str]
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:G6OemKLKABYDIJpgL34qpHL6X4Xy1rOamxWyUMXixhhoAYnXeS/0ZSJZj2ASw1Kmdq2ePzvs7dXKdEAROI2IbhdoPCgm7I2EMWNAlcvhtypjlIQBzIUm5Lj2/9wEoY78t0My3c+H/Xsief0=,iv:PikCyRANoez8bmNSdmjxoPvkZzeNh7ADoKeKLuO3DBI=,tag:TmlK78neuJX3O1vh2Odk+g==,type:str]
    STRIPE_WEBHOOKS_SIGNING_SECRET: ""
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ENC[AES256_GCM,data:HWLXPGt0dBQ6Hgx59LwM4+2cNguTt2DnTEu6YRm28osIIalfATHXROO5PUXp2rP14D0TbWE9JUR0qh3hCWvbaxucP83Gd7oGz2UcD7pcJuo/SlkNrO/QMQsm/PPPdj7H6B77wATL2w4qwtI=,iv:PcnhmGy2AYCw7Q0UhEvDwhSqx7KfTxSpVCDvqqBJU24=,tag:28oYuG5yng9p8jPLpU38cQ==,type:str]
    NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: ENC[AES256_GCM,data:soc5hy35Nx7QqxctPY8H2v8Zt9RLmaB7B1tt7YRkMxQ=,iv:TxjmlN7ljt5ZzFzxSSEmYJXeU0HMkWg7F2BQOPQhNlg=,tag:OkbRV5zmMNSY4tzt4NM6GA==,type:str]
sops:
    lastmodified: "2026-03-15T10:34:31Z"
    mac: ENC[AES256_GCM,data:DjPvk7G5oTrxciPi9GRPltBLr6EIEVPKSdVNmtKgYU6dNPeApihdvY8gXOfEB3u6e0S4G7a72mHebTWAyCvsn9nybbokPcEZ99eaOKJmeLAoBdvF9jKuPhLsVKue/FyEbkzmzYoS8cIidH6fGRgw8T6SJu68fnR78XU7XQi/hd0=,iv:laG1vGE59Wf07R1mpBeT0WdKSlCSbJDBGJYp53O3Lvg=,tag:rHPNTb8yYsAQIDo3EilRBw==,type:str]
    pgp:
        - created_at: "2026-03-15T10:34:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DVb+0b1rhfkgSAQdA7TF9/uXLY7tzCXYcs86+ElWlq3x22MQZZ1P1LY1tGU4w
            KmipCwNxnuDHM5v5bGyyo+pdSxBrwZsUBU0/ScCQO8Aj4S6jFsrvRiic0t5h3LBE
            0l4BGUN/TAfwCgZcAma1xR00WDTEQUwfo0J5Ux3BFGJlH5t8dhPpHnqxLmph+F8p
            mbkEmG0QlTf/FQ2nTeEnnI9FagpcUyqe0eD3KGJ6IrSVzUJ/OoDaUFeFemEAV0Ru
            =zEru
            -----END PGP MESSAGE-----
          fp: 1943731352CACC3B2164E3EED2473B882A11DCBA
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
