apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ozoo-pvc
  namespace: ozoo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
