apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dex
  namespace: dex
spec:
  interval: 5m
  url: https://charts.dexidp.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  chart:
    spec:
      chart: dex
      version: 0.24.x
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: dex
  interval: 1h0m0s
