apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 5m
  url: https://charts.authelia.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  chart:
    spec:
      chart: ./authelia
      version: 0.10.x
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: authelia
  interval: 1h0m0s
