---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-repository
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/AntoineLemarchand/homelab.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-kustomization
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/clusters/proxmox/development
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-repository
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  targetNamespace: development
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-kustomization
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/clusters/proxmox/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-repository
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  targetNamespace: production
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-kustomization
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/clusters/proxmox/infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-repository
  targetNamespace: infrastructure
